### ISSUE TITLE
Ideal bit depth for distance in the range of 11.5 kilometers

### ISSUE THREAD

**Issue by winash12** [yinqiwen/geohash-int#10]
[https://en.wikipedia.org/wiki/Geohash](url) From this URL I would like to know what is the ideal precision for calculating distances in the range of 11.5 kms(0.1 degrees).

I thought it was bit depth 19 but it seems when I calculate the total number of bits from geohash-int I am not entirely clear
```
# query geohash
lonTest = 172.76843
 latTest = 61.560745
 geohashTest = geoHash.encode(lonTest,latTest,19)
 bitsTestOriginal =    geohashTest["bits"]
 
q = 270171420400
bitd_q = math.ceil(math.log(q, 2))
#
print("total number of bits")
print(bitd_q)
The answer is 38 
```
This prints 38 as bit depth which means   0.00034 degrees and it is a bit surprising because I was expecting 19 bits but since you are saying 2 bits for each step that makes sense.

So for 0.1 degrees (11.5 kilometers) what is the ideal bit depth ?

**Comment by yinqiwen** [comment]
https://github.com/yinqiwen/ardb/wiki/Spatial-Index
this wiki list how to choose geohash bits by radius meters

**Comment by winash12** [comment]
Assuming this is my query point
```
 lonTest = 172.76843
 latTest = 61.560745
 geohashTest = geoHash.encode(lonTest,latTest,19)
 bitsTestOriginal =    geohashTest["bits"]
 print(bitsTestOriginal) 
```
I get this value - 270171420400

Now as you said yesterday I must shift this by 14 bits so I get 4426488551833600
Now this is the geohash of my query point.

Assuming my data point is 

``` 
gridLon = 172.85000000008023
gridLat = 61.65143600000049
geohashTest = geoHash.encode(lonTest,latTest,26)
geohash 4426491236881515
```
Using a skip list what should be the upper bound for a possible range query  for this data point assuming lower bound is 4426488551833600 ?


If you subtract  4426491236881515 and 4426488551833600 you get 2685047915 which is a very huge number but these points are very very close. What is the reason ?

**Comment by winash12** [comment]
For a  geohash q at bit  depth x the   range at bit depth y (y >= x)  in binary representation is [q followed by (y-x) zeros, q followed by (y-x) ones

So if q = 1001 is x = 4 bit geohash in binary, then its 8 bit geohash range is [10010000, 10011111]

So in my case the geohash range at bit depth 26 for geohash at bit 19 is
[426488551833600, 442648855184179]
The upper bound is calculated as  - (lowerboundgeohash << 2*7) + (1<<(2*7)-1)

But this is still not in range of data geohash 4426491236881515 although distance wise  it is certainly within the range. Where  is the mistake in my range calculation ?
