### ISSUE TITLE
geohash-int encoding not providing correct range queries

### ISSUE THREAD

**Issue by winash12** [yinqiwen/geohash-int#11]
@yinqiwen I believe there is a bug in your code.

I went to this github site and downloaded their geohash encoding software - https://github.com/hkwi/python-geohash/blob/master/geohash.py and I have some results to share. It would be great if you can fix the bug because I would like to continue using your code -

```
import geohash as gh

#query geohash
lonTest = 172.76843
latTest = 61.560745

geoha = gh.encode_uint64(latTest,lonTest)

gg = geoha >> 45
print(gg)
print(gg.bit_length())
# Showing values below of print
#515311
#19


#data geohash
gridLon = 172.85000000008023
gridLat = 61.65143600000049

geoha1 = gh.encode_uint64(gridLat,gridLon)

gg1 = geoha1 >> 38

print(gg1)
print(gg1.bit_length())
# Showing values below of gg1 and bit length of gg1
#65959859
#26
rangeMin = gg << 7
rangeMax = rangeMin + (1 << (26-19) - 1) 

print(rangeMax-rangeMin,rangeMin,rangeMax,gg1)
#64 65959808 65959872 65959859
assert(rangeMin <=gg1 and gg1 < rangeMax)
```

As you can see gg1 is "in range" of rangeMin and rangeMax. With your code I am not able to reproduce this. Can you show where I am wrong and your code is correct ?

**Comment by yinqiwen** [comment]
to use geohash-int search by a radius value , u need to search the 8 neighbors, not only the geohash box area.

**Comment by winash12** [comment]
Still not getting it in a range query. When I add the data geohashes to a skip list(not the query geohashes) must I add the 8 neighbors as well to the skip list in order for a range query to work ?

Tomorrow I will reduce the number of geohashes I am adding to the skip list and then do the test again. At the moment I am unable to do a successful range query. I can share my code offline if you request.

**Comment by yinqiwen** [comment]
geohash value represent a box in the map, if a point is at the edge of the box, u need to search the neighbors box to find the nearest points, and a box in the 2D map have 8 neighbors.

**Comment by winash12** [comment]
I will put my code in a github site(my skip list code and your geohash code) in the future after some more testing. Then you can download, build and then verify yourself. Or suggest modifications.
