### ISSUE TITLE
Adding  1 to geohash-int

### ISSUE THREAD

**Issue by winash12** [yinqiwen/geohash-int#8]
I closed this issue - [https://github.com/yinqiwen/geohash-int/issues/7](url) but I think I am correct on that one. When you add 1 to geohash value generated by encode you are no longer getting unique numbers. Is that all right ? I have a range of lat,lon and then I am calculating the geohash of each lat,lon. Then I am calculating the 9 pairs(geohash, geohash +1). This is generating non unique values. Is that OK ? Problem arises when I need to decode the encoded values.

**Comment by yinqiwen** [comment]
use a data structure {geohash, lat, lon} to represent a uniq point, u only need to make sure it's uniq not geohash value.
