### ISSUE TITLE
geohash range query clarification

### ISSUE THREAD

**Issue by winash12** [yinqiwen/geohash-int#9]
Assuming this is my query point 
```
 lonTest = 172.76843
 latTest = 61.560745
 geohashTest = geoHash.encode(lonTest,latTest,19)
 bitsTestOriginal =    geohashTest["bits"]
 print(bitsTestOriginal) 
```
I get this value - 270171420400

If I left bit shift this by 7 I get 34581941811200

This query coordinate should be in the range of the grid coordinate (0.1 degrees or 11.5 kms)
```
 
gridLon = 172.85000000008023
gridLat = 61.65143600000049
geohashTest = geoHash.encode(lonTest,latTest,26)
geohash 4426491236881515
```
This is at bit depth 26

As you can see my query point is not in "range" of the grid coordinate. Where is the mistake in my understanding ?

**Comment by yinqiwen** [comment]
it can not shit by an odd number since 2 bits represent a geohash step, u must shit the value by step *2
```
       270171420400  <<  (2*7)    = 4426488551833600
```

**Comment by winash12** [comment]
@yinqiwen Thank you ! That clears so many issues !!!
